# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - prod

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 16
        # Set this option if you want the action to check for the latest available version that satisfies the version spec
        check-latest: true
        
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: generate files
      env:
        BUGSNAG: ${{ secrets.BUGSNAG }}
        TRACKING: ${{ secrets.TRACKING }}
        GOVBAR: ${{secrets.GOVBAR}}
        GSITEVERIF: ${{secrets.GSITEVERIF}}
      run: | 
        cd $GITHUB_WORKSPACE
        npm install
        bash ./build.sh
    - name: Upload dist as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
